### ISSUE TITLE
[flodash] unnecessary flutter dependency 

### ISSUE THREAD

**Issue by tsouza** [sliit-foss/dart-cookbook#91]
The `flodash` library is purely for manipulating data structures. Can we drop it's flutter dependency?

**Comment by Akalanka47000** [comment]
> The `flodash` library is purely for manipulating data structures. Can we drop it's flutter dependency?

Hi @tsouza, Sorry for the late reply. Flutter has been removed from the dependency list and a prerelease version has been published. Will be promoting it to stable in some time. Thank you for raising this. It was on the bucket list but was lost down the line.
